FROM datamachines/cudnn_tensorflow_opencv:11.6.2_2.9.1_3.4.16-20220815

RUN python3 -m pip install --upgrade pip

RUN python3 -m pip install numpy matplotlib seaborn pandas notebook pyarrow scikit-learn
